// export const genres = [
//   "abstract-wallpaper-wallpaper",
//   "animals-wallpaper",
//   "architecture-wallpaper",
//   "art-wallpaper",
//   "astronomy-wallpaper",
//   "backgrounds-wallpaper",
//   "biology-wallpaper",
//   "cats-wallpaper",
//   "city-wallpaper",
//   "food-wallpaper",
//   "fashion-wallpaper",
//   "nature-wallpaper",
//   "sports-wallpaper",
//   "technics-wallpaper",
//   "transport-wallpaper",
//   "cars-wallpaper",
//   "generative-art-wallpaper",
//   "sketch-wallpaper",
//   "nfts-wallpaper",
//   "blockchain-wallpaper",
//   "programming-wallpaper",
//   "gaming-wallpaper",
//   "music-wallpaper",
//   "people-wallpaper",
//   "fashion-design",
//   "movies-wallpaper",
//   "web-series-wallpaper",
//   "literature-wallpaper",
//   "history-wallpaper",
//   "education-wallpaper",
//   "science-wallpaper",
//   "space-wallpaper",
//   "nature-landscapes-wallpaper",
//   "people-portraits-wallpaper",
//   "art-design-wallpaper",
//   "education-art-wallpaper",
//   "paintings-wallpaper",
//   "photography-wallpaper",
//   "nature-wildlife--wallpaper",
//   "waterfall-wallpaper",
//   "sea-wallpaper",
//   "mountains",
//   "rainfall-wallaper",
// ];

export const genres = [
  "nft",
  "nft-wallpaper",
  "nft-wallpaper-wallpaper",
  "pattern",
  "Experimental",
  "Textures",
  "computer-art",
  "3d-models",
  "pixelated-2d",
  "three-js-models",
];
